---
image_resource:
  type: docker-image
  source:
    repository: licensefinder/license_finder
    tag: latest
platform: linux
inputs:
- name: lf-git
- name: lf-release
outputs:
- name: version
run:
  path: lf-git/ci/scripts/check-version-and-get-tags.sh
